### ISSUE TITLE
Is this supposed to address the Blender window freeze when the Qt window is open?

### ISSUE THREAD

**Issue by mikebourbeauart** [huntfx/vfxwindow#1]
I'm just starting out on some PySide2 pipeline dev with Blender and I'm running into the issue where Blender's window freezes or doesn't update when the Qt window is open. 

Does vfxwindow address that or do we still need to handle that on our own? 

I've found a few workarounds, but they're not perfect- for example I can get Blender to not freeze by following this [method](https://www.youtube.com/watch?v=QYgHyi7jd9c), but if I try to move the main Blender window the whole program freezes. Same result with this [method](https://gitlab.com/snippets/1881226). 

Seems like a cool package though, I'll look into implementing it into my project.

**Comment by huntfx** [comment]
Hey, I've not done too much testing on Blender, but I think I remember coming across that issue and solving it :)

If you start using this, I made a page detailing how to use a few of the features - https://github.com/Peter92/vfxwindow/wiki/Quick-Start

**Comment by mikeustwo** [comment]
[Just asked for more help here as well](https://blender.stackexchange.com/questions/178860/qt-pyside2-pyqt-windows-freezes-all-blender-windows-when-i-try-to-move-blenders), not sure I know enough about how Blender or threads work to effectively solve this at the moment.

**Comment by mikebourbeauart** [comment]
[Just asked for more help here](https://blender.stackexchange.com/questions/178860/qt-pyside2-pyqt-windows-freezes-all-blender-windows-when-i-try-to-move-blenders) as well, not sure I know enough about how Blender or threads work to effectively solve this at the moment. Also, thanks for the wiki link! I forget they exist (so used to just reading the README's)

**Comment by huntfx** [comment]
To be honest I forgot about the wiki until you posted aha, it just dawned on me I didn't seem to have much documentation, so I checked in there and found some from half a year ago.

The point of this module is to do the solving for you. If you write your window to inherit `VFXWindow`, then calling `win.show()` will perform whatever steps are needed to open it without locking Blender. Remember that it inherits `QMainWindow` and not `QDialog` like in the example you linked, so some lines will have to be changed.

**Comment by mikebourbeauart** [comment]
Thanks for clearing that up. I'll give it another go.
