### ISSUE TITLE
Support for other operating systems

### ISSUE THREAD

**Issue by garysb** [huntfx/vfxwindow#3]
In the __init__.py checks are getting made on sys.executable that restrict proper functionality to windows only (checking if maya.exe is the executable for example).

Would you like me to provide a pull request for a more generic way of doing the checks? From what I see, the reason for these is to make sure its not a module with the same name not within the program, and to differentiate between maya and mayapy?

**Comment by huntfx** [comment]
Hey, yeah you're correct in that mayapy was the main reason I started doing it that way. There's also the case of Houdini however, where Maya is actually able to import the `hou` module, so I couldn't solely rely on if something can be imported (there could be other similar cases that crop up in the future).

If you do have a better idea though I'd be all ears, I'm aware my method isn't perfect, it's just the safest way I could think of at the time.

**Comment by gpijat** [comment]
Hello @huntfx, I'm currently working on a project that is supposed to run on most VFX platforms and I came across your project.
I'm thinking about using it but as of today, it's not working in Linux which is one of my requirement. (Don't know about MacOs but based on things like `'maya.exe' in sys.executable` I would assume not).

The reason why I'm answering here is that I've worked on something similar and it seems to work well so I was wondering if I could submit a pull request to contribute to your project ? It's nothing crazy, it's based on regular expression searching for patterns in sys.executable. 
I already cloned the repository and made my changes on a local branch for testing purpose and It's working great in Linux, and I also have support for Unreal Engine 5 (Windows) that comes "for free".

Thanks in advance and happy Monday !

Greg.

**Comment by huntfx** [comment]
Hey, sorry @gpijat, I'd completely missed this message, I'd been on holiday that week so had a lot of emails to skim over lol.

Anyway, I've just released those changes so 1.8 is the official version now (thanks again for the help), will mark this issue as solved since it works on Linux now 😄
