### ISSUE TITLE
Latest release (1.6.4) is missing a lot of the latest improvements

### ISSUE THREAD

**Issue by gpijat** [huntfx/vfxwindow#6]
Hello @huntfx,

The latest release who's the default one installed with pip is missing a lot of the latest improvements.
One I have for instance (Linux Mint - Maya 2022.4) is here: https://github.com/huntfx/vfxwindow/blob/679c4348ff3956e4be47994135888544d57409dc/vfxwindow/maya.py#L488
Error: `# Error: TypeError: file /home/gpij/Workspace/vfxwindow/vfxwindow/maya.py line 488: '<' not supported between instances of 'str' and 'int' # `

I think this is a really specific issue to Maya 2022 but It's a good example for this current issue as it's addressed on the master branch.

PS: To run on linux I changed `https://github.com/huntfx/vfxwindow/blob/679c4348ff3956e4be47994135888544d57409dc/vfxwindow/__init__.py#L64` to use `maya.bin` instead of `maya.exe`. As a temporary workaround to test the rest of the library. 
For Linux, I'm working on some changes that I would like to submit to your approval, I'm talking about it here: https://github.com/huntfx/vfxwindow/issues/3#issuecomment-1752342108

Thank you.

**Comment by huntfx** [comment]
Ah sorry I totally missed this, I'd just got back from holiday so had a week's worth of unread emails.
All fixed now anyway as you know with 1.8 to be released soon :)
